matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - GITHUB_PAGES=false

    - os: linux
      services: docker
      language: node_js
      node_js: "10"
      env:
        - GITHUB_PAGES=true

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -n "$TRAVIS_TAG" ]; then
      docker run --rm \
        --env-file <(env | grep -vE '\r|\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm install && npm run bundle:linux && npm run bundle:windows"
    elif [ -n "$TRAVIS_TAG" ]; then
      npm run bundle:mac
    else
      echo "Not a tagged build."
    fi

before_deploy:
  ng build --prod --base-href="/eve-electron-tools" --deploy-url "/eve-electron-tools"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
      condition: "$GITHUB_PAGES = true"
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: release/eve-electron-tools*
    overwrite: true
    skip_cleanup: true
    on:
      tags: true